kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: /var/lib/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
clusterDomain: kubernetes.local
clusterDNS:
  - 10.0.0.10
cgroupDriver: systemd
runtimeRequestTimeout: "15m"
tlsCertFile: /var/lib/kubernetes/pki/controlplane.crt
tlsPrivateKeyFile: /var/lib/kubernetes/pki/controlplane.key
registerNode: true