kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: /var/lib/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
cgroupDriver: systemd
clusterDomain: "kubernetes.local"
clusterDNS:
  - 10.0.0.10
registerNode: true
resolvConf: /etc/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: "15m"
# we are telling kubelet to bootstrap
serverTLSBootstrap: true